name: combustivel_app
description: Aplicativo de controle de combustível
version: 1.0.2+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  home_widget: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
